### ISSUE TITLE
Error building when src folder is present on App_Resources/Android

### ISSUE THREAD

**Issue by apexJCL** [bradmartin/nativescript-lottie#23]
```
Gradle build...
         + applying user-defined configuration from /home/carlos/Documentos/Nativescript/<appname>/dist/app/App_Resources/Android/app.gradle
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'debugCompile' in project ':app' is deprecated. Use 'debugImplementation' instead.
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: /home/carlos/Documentos/Nativescript/<appname>/dist/node_modules/nativescript-background-http/platforms/android/nativescript_background_http.aar
         + adding aar plugin dependency: /home/carlos/Documentos/Nativescript/<appname>/dist/node_modules/nativescript-camera/platforms/android/nativescript_camera.aar
         + adding aar plugin dependency: /home/carlos/Documentos/Nativescript/<appname>/dist/node_modules/nativescript-image-cache-it/platforms/android/nativescript_image_cache_it.aar
         + adding aar plugin dependency: /home/carlos/Documentos/Nativescript/<appname>/dist/node_modules/nativescript-imagepicker/platforms/android/nativescript_imagepicker.aar
         + adding aar plugin dependency: /home/carlos/Documentos/Nativescript/<appname>/dist/node_modules/nativescript-modal-datetimepicker/platforms/android/nativescript_modal_datetimepicker.aar
         + adding aar plugin dependency: /home/carlos/Documentos/Nativescript/<appname>/dist/node_modules/nativescript-plugin-firebase/platforms/android/firebase-release.aar
         + adding aar plugin dependency: /home/carlos/Documentos/Nativescript/<appname>/dist/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
/home/carlos/Documentos/Nativescript/<appname>/dist/platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:43: AAPT: error: resource drawable/icon (aka <appname>:drawable/icon) not found.
    
/home/carlos/Documentos/Nativescript/<appname>/dist/platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:43: error: resource drawable/icon (aka <appname>:drawable/icon) not found.
error: failed processing manifest.

Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
        at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
```

This happens when I try to do a clean build having the folder `src` located in `App_Resources/Android`.

Steps to be able to compile:

+ Remove src folder
+ Build
+ Restore folder

So everytime I do a clean build, I need to remove the folder, otherwise it complains.

Using:

+ NS v4
+ NS-Vue | NS-NG

**Comment by FranciZ** [comment]
Running into the same issue. Can't use this library unless I copy the lottie json files directly into the platforms folder at:

`platforms/android/app/src/main/assets`

**Comment by bradmartin** [comment]
I was able to build a new app with the latest version of the plugin and using NS 4x, below is my build ouput:

```Brads-MBP:lottie bradmartin$ tns plugin add nativescript-lottie

Support for Node.js ^6.0.0 is deprecated and will be removed in one of the next releases of NativeScript. Please, upgrade to the latest Node.js LTS version.

+ nativescript-lottie@2.0.0
added 1 package from 4 contributors in 2.456s
Successfully installed plugin nativescript-lottie.
Brads-MBP:lottie bradmartin$ tns build android

Support for Node.js ^6.0.0 is deprecated and will be removed in one of the next releases of NativeScript. Please, upgrade to the latest Node.js LTS version.

Copying template files...
⠙ Installing tns-android⠇ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠏ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠋ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠙ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠹ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠸ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠼ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠴ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠦ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠧ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠇ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠏ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠋ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠙ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠹ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠸ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠼ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠴ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠦ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠧ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠇ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠏ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠋ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠙ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠹ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠸ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠼ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠴ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠦ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠧ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠇ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠏ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:tns-android: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des+ tns-android@4.1.1
added 1 package in 4.511s
⠙ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠹ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠸ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠼ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠴ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠦ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠧ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠇ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠏ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠋ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠙ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠹ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠸ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠼ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠴ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠦ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠧ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠇ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠏ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠋ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠙ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/⠹ ⸨       ░░░░░░░░░░░⸩ ⠸ extract:babel-traverse: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/+ babel-traverse@6.26.0
added 24 packages from 10 contributors in 5.961s
⠹ ⸨░░░░░░░░░░░░░░░░░░⸩ ⠦ fetchMetadata: sill removeObsoleteDep removing to-fast-properties@1.0.3 from the tree as its been replaced by a newer vers⠦ ⸨       ░░░░░░░░░░░⸩ ⠙ extract:babel-types: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠧ ⸨       ░░░░░░░░░░░⸩ ⠙ extract:babel-types: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠇ ⸨       ░░░░░░░░░░░⸩ ⠙ extract:babel-types: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠏ ⸨       ░░░░░░░░░░░⸩ ⠙ extract:babel-types: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠋ ⸨       ░░░░░░░░░░░⸩ ⠙ extract:babel-types: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠙ ⸨       ░░░░░░░░░░░⸩ ⠙ extract:babel-types: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠹ ⸨       ░░░░░░░░░░░⸩ ⠙ extract:babel-types: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠸ ⸨       ░░░░░░░░░░░⸩ ⠙ extract:babel-types: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠼ ⸨       ░░░░░░░░░░░⸩ ⠙ extract:babel-types: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des⠴ ⸨       ░░░░░░░░░░░⸩ ⠙ extract:babel-types: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Des+ babel-types@6.26.0
updated 1 package in 2.315s
⠧ ⸨       ░░░░░░░░░░░⸩ ⠧ extract:babylon: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop⠇ ⸨       ░░░░░░░░░░░⸩ ⠧ extract:babylon: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop⠏ ⸨       ░░░░░░░░░░░⸩ ⠧ extract:babylon: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop⠋ ⸨       ░░░░░░░░░░░⸩ ⠧ extract:babylon: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop⠙ ⸨       ░░░░░░░░░░░⸩ ⠧ extract:babylon: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop⠹ ⸨       ░░░░░░░░░░░⸩ ⠧ extract:babylon: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop⠸ ⸨       ░░░░░░░░░░░⸩ ⠧ extract:babylon: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop⠼ ⸨       ░░░░░░░░░░░⸩ ⠧ extract:babylon: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop⠴ ⸨       ░░░░░░░░░░░⸩ ⠧ extract:babylon: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop⠦ ⸨       ░░░░░░░░░░░⸩ ⠧ extract:babylon: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop⠧ ⸨       ░░░░░░░░░░░⸩ ⠧ extract:babylon: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop+ babylon@6.18.0
updated 1 package in 2.535s
⠸ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:lazy: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop/lo⠼ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:lazy: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop/lo⠴ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:lazy: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop/lo⠦ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:lazy: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop/lo⠧ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:lazy: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop/lo⠇ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:lazy: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop/lo⠏ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:lazy: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop/lo⠋ ⸨       ░░░░░░░░░░░⸩ ⠼ extract:lazy: verb lock using /Users/bradmartin/.npm/_locks/staging-f9654dc9f1632532.lock for /Users/bradmartin/Desktop/lo+ lazy@1.0.11
added 1 package from 1 contributor in 1.724s
Project successfully created.
Executing before-prepare hook from /Users/bradmartin/Desktop/lottie/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.7.2
Preparing project...
Successfully prepared plugin nativescript-lottie for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (android)
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from /Users/bradmartin/Desktop/lottie/app/App_Resources/Android/app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: /Users/bradmartin/Desktop/lottie/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.a
ar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Project successfully built.```

![test](https://user-images.githubusercontent.com/6006148/40897274-cd413d1a-677f-11e8-96b9-a19273f1da74.png)


With the following markup:

```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" 
    xmlns:Lottie="nativescript-lottie" navigatingTo="navigatingTo" class="page">
    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>
    <StackLayout class="p-20">
        <Label text="Tap the button" class="h1 text-center"/>
        <Lottie:LottieView src="sample.json" height="150" width="100" loop="true" autoPlay="true" loaded="lottieloaded" />
        <Button text="TAP" tap="{{ onTap }}" class="btn btn-primary btn-active"/>
        <Label text="{{ message }}" class="h2 text-center" textWrap="true"/>
    </StackLayout>
</Page>
```

If you're having build issues, then you likely have some cache problem locally, a version not updated or something internal in the build that I have not ran into personally. 

I'd try on a new project using the 4.1.0 CLI (latest stable release) and see if you can duplicate my results, if you can then you know your project has something being left over during your build. This can vary from OS to OS and machine to machine which sucks. I've recently had to help a colleague on a project I updated and it worked fine with no issues on my machine and then he spent 5 hours trying to get his to build, after a day he just restarted, removed the `platforms` of the project and then it worked with no changes. Best of luck, if you can reproduce let me know.
